@startuml
@startuml

actor Analys as "Analyst"

rectangle WorldDB as "World database"

rectangle "HR System" {
    usecase UC1 as "Generate City report"

    usecase UC2 as "All the cities in the
    world organised by largest
    population to smallest."

    Analys - UC1
    UC1 ..> UC2 : include
    UC1 - WorldDB
}
@enduml

//d123