@startuml
@startuml

actor Analys as "Analyst"

rectangle WorldDB as "World database"

rectangle "HR System" {
    usecase UC1 as "Provide spoken languages information"

    usecase UC2 as "Percentage of world
    population who speak Chinese."

    Analys - UC1
    UC1 ..> UC2 : include
    UC1 - WorldDB
}
@enduml


//d123